version: '3'
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: toan
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - /home/toan/jenkins/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
